server:
  port: 8181
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rentdb?createDatabaseIfNotExist=true
    username: ryan
    password: rpass
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: create
security:
  oauth2:
    resource:
      token-info-uri: http://localhost:9191/oauth/check_token
    client:
      client-id: mobile
      client-secret: pin
